[package]
name = "lstmburn-sw8"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "~0.16", features = ["train", "wgpu", "vision"] }
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

